version: 5.1.0
variant: default
logo: /img/logo.jpg
head:
    favicon: /img/favicon.svg
    manifest:
        name: Adam Farrell's Blog
        short_name: Adam's Blog
        start_url: https://adamfarrell.org
        theme_color: "#cfe0fc"
        background_color: "#cfe0fc"
        display: standalone
    open_graph:
        type: blog
    meta:
        - ''
    rss: /atom.xml
navbar:
    menu:
        Home: /
        Archives: /archives
        Tags: /tags
        About: /about
    links:
        GitHub:
            icon: fab fa-github
            url: https://github.com/adam-farrell
        LinkedIn:
            icon: fab fa-linkedin
            url: https://linkedin.com/in/adam-farrell-92684829
        Medium:
            icon: fab fa-medium
            url: https://medium.com/@adam.farrell
footer:
    copyright: © Adam Farrell
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
search:
    type: insight
    index_pages: true
donates: []
sidebar:
    left:
        sticky: true
    right:
        sticky: false
widgets:
    -
        type: recent_posts
        position: right
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id:
    bing_webmaster:
        tracking_id:
    busuanzi: false
    cnzz:
        id:
        web_id:
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id:
    hotjar:
        site_id:
    katex: false
    mathjax: false
    outdated_browser: false
    pjax: false
    progressbar: true
    statcounter:
        project:
        security:
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
